name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Flask Test
      id: flask-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Flask Test
        setup-command: pip install -r requirements.txt
        command: pytest --pylint
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FLASK-TEST_RESULTS: "${{steps.flask-test.outputs.result}}"
      with:
        runners: flask-test
